"""Статические ограничения полей моделей приложения recipes."""

TAG_NAME_MAX_LENGTH = 32
TAG_SLUG_MAX_LENGTH = 32

INGREDIENT_NAME_MAX_LENGTH = 128
INGREDIENT_UNIT_MAX_LENGTH = 64

RECIPE_NAME_MAX_LENGTH = 256
RECIPE_SHORT_CODE_MAX_LENGTH = 16
RECIPE_SHORT_CODE_GENERATED_LENGTH = 10
