# Generated by Django 4.2.29 on 2026-04-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.UniqueConstraint(
                fields=("name", "measurement_unit"),
                name="recipes_ingredient_name_unit_uniq",
            ),
        ),
    ]
