# Generated by Django 4.2.29 on 2026-04-05 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("recipes", "0003_refactor_models"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Subscription",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "author",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="subscribers",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Автор",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="subscriptions",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Подписчик",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Подписка",
                        "verbose_name_plural": "Подписки",
                        "db_table": "recipes_subscription",
                    },
                ),
                migrations.AddConstraint(
                    model_name="subscription",
                    constraint=models.UniqueConstraint(
                        fields=("user", "author"),
                        name="users_subscription_user_author_uniq",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="subscription",
                    constraint=models.CheckConstraint(
                        check=models.Q(
                            ("user", models.F("author")),
                            _negated=True,
                        ),
                        name="users_subscription_not_self",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
