# Generated by Django 4.2.29 on 2026-04-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_refactor_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("email",),
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
